#version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://bakytdeveloper:first_project@firstproject.2o2xk.mongodb.net/firstProject?retryWrites=true&w=majority
      - PORT=3001
    volumes:
      - .:/usr/src/app
